/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GtkWidget *vbox1;
  GtkWidget *hbox1;
  GtkWidget *vbox4;
  GtkWidget *figure_events;
  GtkWidget *figure;
  GtkWidget *help_label;
  GtkWidget *vbox2;
  GtkWidget *frame2;
  GtkWidget *alignment2;
  GtkWidget *table1;
  GtkWidget *label6;
  GtkWidget *angle_deg_entry;
  GtkWidget *angle_rad_entry;
  GtkWidget *label5;
  GtkWidget *label2;
  GtkWidget *frame3;
  GtkWidget *alignment3;
  GtkWidget *table2;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *trig_tan_entry;
  GtkWidget *trig_cos_entry;
  GtkWidget *trig_sin_entry;
  GtkWidget *label9;
  GtkWidget *label3;
  GtkWidget *explain_label;
  GtkWidget *hbuttonbox1;
  GtkWidget *revert_button;
  GtkWidget *alignment4;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label17;
  GtkWidget *about_button;
  GtkWidget *close_button;

  main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (main_window), "The Unit Circle");
  gtk_window_set_position (GTK_WINDOW (main_window), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (main_window), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (main_window), FALSE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (main_window), vbox1);

  hbox1 = gtk_hbox_new (FALSE, 6);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 6);

  vbox4 = gtk_vbox_new (FALSE, 6);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox4, FALSE, TRUE, 0);

  figure_events = gtk_event_box_new ();
  gtk_widget_show (figure_events);
  gtk_box_pack_start (GTK_BOX (vbox4), figure_events, FALSE, TRUE, 0);
  gtk_widget_set_size_request (figure_events, 420, 420);
  gtk_event_box_set_above_child (GTK_EVENT_BOX (figure_events), TRUE);

  figure = gtk_drawing_area_new ();
  gtk_widget_show (figure);
  gtk_container_add (GTK_CONTAINER (figure_events), figure);
  gtk_widget_set_size_request (figure, 420, 420);

  help_label = gtk_label_new ("<i>Click the mouse in the figure above to change the angle \316\270,\nand see how it affects the values at right.\n\nEdit the values at right to see how the angle changes.</i>\n");
  gtk_widget_show (help_label);
  gtk_box_pack_start (GTK_BOX (vbox4), help_label, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (help_label), TRUE);
  gtk_label_set_justify (GTK_LABEL (help_label), GTK_JUSTIFY_CENTER);

  vbox2 = gtk_vbox_new (FALSE, 6);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox2, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 6);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox2), frame2, FALSE, TRUE, 0);
  gtk_frame_set_label_align (GTK_FRAME (frame2), 1, 0.5);
  gtk_frame_set_shadow_type (GTK_FRAME (frame2), GTK_SHADOW_NONE);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (frame2), alignment2);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 0, 0, 12, 0);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (alignment2), table1);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 4);

  label6 = gtk_label_new ("radians:");
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table1), label6, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 1, 0.5);

  angle_deg_entry = gtk_entry_new ();
  gtk_widget_show (angle_deg_entry);
  gtk_table_attach (GTK_TABLE (table1), angle_deg_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (angle_deg_entry), 6);

  angle_rad_entry = gtk_entry_new ();
  gtk_widget_show (angle_rad_entry);
  gtk_table_attach (GTK_TABLE (table1), angle_rad_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (angle_rad_entry), 6);

  label5 = gtk_label_new ("degrees:");
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table1), label5, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 1, 0.5);

  label2 = gtk_label_new ("<b>Angular\nMeasurements</b>");
  gtk_widget_show (label2);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label2);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (label2), 0, 5);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox2), frame3, FALSE, TRUE, 0);
  gtk_frame_set_label_align (GTK_FRAME (frame3), 1, 0.5);
  gtk_frame_set_shadow_type (GTK_FRAME (frame3), GTK_SHADOW_NONE);

  alignment3 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (frame3), alignment3);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment3), 0, 0, 12, 0);

  table2 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (alignment3), table2);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 4);

  label10 = gtk_label_new ("cos <i>\316\270</i>:");
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table2), label10, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label10), 1, 0.5);

  label11 = gtk_label_new ("tan <i>\316\270</i>:");
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table2), label11, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label11), 1, 0.5);

  trig_tan_entry = gtk_entry_new ();
  gtk_widget_show (trig_tan_entry);
  gtk_table_attach (GTK_TABLE (table2), trig_tan_entry, 1, 2, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (trig_tan_entry), 6);

  trig_cos_entry = gtk_entry_new ();
  gtk_widget_show (trig_cos_entry);
  gtk_table_attach (GTK_TABLE (table2), trig_cos_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (trig_cos_entry), 6);

  trig_sin_entry = gtk_entry_new ();
  gtk_widget_show (trig_sin_entry);
  gtk_table_attach (GTK_TABLE (table2), trig_sin_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (trig_sin_entry), 6);

  label9 = gtk_label_new ("sin <i>\316\270</i>:");
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table2), label9, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label9), 1, 0.5);

  label3 = gtk_label_new ("<b>Trigonometric\nValues</b>");
  gtk_widget_show (label3);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label3);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (label3), 0, 5);

  explain_label = gtk_label_new ("<i>A \"unit circle\" has a\nradius of exactly 1.\n\nAn angle line drawn\nfrom the origin will\npass through the\ncircle at coordinates\n(x, y) equal to the\ncosine (x) and sine\n(y) of the angle.</i>");
  gtk_widget_show (explain_label);
  gtk_box_pack_start (GTK_BOX (vbox2), explain_label, TRUE, TRUE, 0);
  gtk_label_set_use_markup (GTK_LABEL (explain_label), TRUE);
  gtk_label_set_justify (GTK_LABEL (explain_label), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (explain_label), TRUE);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbuttonbox1, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox1), 6);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox1), 6);

  revert_button = gtk_button_new ();
  gtk_widget_show (revert_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), revert_button);
  GTK_WIDGET_SET_FLAGS (revert_button, GTK_CAN_DEFAULT);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (revert_button), alignment4);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-revert-to-saved", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic ("_Reset");
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox2), label17, FALSE, FALSE, 0);

  about_button = gtk_button_new_from_stock ("gtk-about");
  gtk_widget_show (about_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), about_button);
  GTK_WIDGET_SET_FLAGS (about_button, GTK_CAN_DEFAULT);

  close_button = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (close_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), close_button);
  GTK_WIDGET_SET_FLAGS (close_button, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) main_window, "realize",
                    G_CALLBACK (on_main_window_realize),
                    NULL);
  g_signal_connect ((gpointer) main_window, "delete_event",
                    G_CALLBACK (on_main_window_delete_event),
                    NULL);
  g_signal_connect ((gpointer) main_window, "destroy_event",
                    G_CALLBACK (on_main_window_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) figure_events, "event",
                    G_CALLBACK (on_figure_events_event),
                    NULL);
  g_signal_connect ((gpointer) figure, "expose_event",
                    G_CALLBACK (on_figure_expose_event),
                    NULL);
  g_signal_connect ((gpointer) angle_deg_entry, "changed",
                    G_CALLBACK (on_angle_deg_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) angle_rad_entry, "changed",
                    G_CALLBACK (on_angle_rad_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) trig_tan_entry, "changed",
                    G_CALLBACK (on_trig_tan_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) trig_cos_entry, "changed",
                    G_CALLBACK (on_trig_cos_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) trig_sin_entry, "changed",
                    G_CALLBACK (on_trig_sin_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) revert_button, "clicked",
                    G_CALLBACK (on_revert_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) about_button, "clicked",
                    G_CALLBACK (on_about_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) close_button, "clicked",
                    G_CALLBACK (on_close_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, main_window, "main_window");
  GLADE_HOOKUP_OBJECT (main_window, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (main_window, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (main_window, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (main_window, figure_events, "figure_events");
  GLADE_HOOKUP_OBJECT (main_window, figure, "figure");
  GLADE_HOOKUP_OBJECT (main_window, help_label, "help_label");
  GLADE_HOOKUP_OBJECT (main_window, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (main_window, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (main_window, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (main_window, table1, "table1");
  GLADE_HOOKUP_OBJECT (main_window, label6, "label6");
  GLADE_HOOKUP_OBJECT (main_window, angle_deg_entry, "angle_deg_entry");
  GLADE_HOOKUP_OBJECT (main_window, angle_rad_entry, "angle_rad_entry");
  GLADE_HOOKUP_OBJECT (main_window, label5, "label5");
  GLADE_HOOKUP_OBJECT (main_window, label2, "label2");
  GLADE_HOOKUP_OBJECT (main_window, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (main_window, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (main_window, table2, "table2");
  GLADE_HOOKUP_OBJECT (main_window, label10, "label10");
  GLADE_HOOKUP_OBJECT (main_window, label11, "label11");
  GLADE_HOOKUP_OBJECT (main_window, trig_tan_entry, "trig_tan_entry");
  GLADE_HOOKUP_OBJECT (main_window, trig_cos_entry, "trig_cos_entry");
  GLADE_HOOKUP_OBJECT (main_window, trig_sin_entry, "trig_sin_entry");
  GLADE_HOOKUP_OBJECT (main_window, label9, "label9");
  GLADE_HOOKUP_OBJECT (main_window, label3, "label3");
  GLADE_HOOKUP_OBJECT (main_window, explain_label, "explain_label");
  GLADE_HOOKUP_OBJECT (main_window, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (main_window, revert_button, "revert_button");
  GLADE_HOOKUP_OBJECT (main_window, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (main_window, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (main_window, image2, "image2");
  GLADE_HOOKUP_OBJECT (main_window, label17, "label17");
  GLADE_HOOKUP_OBJECT (main_window, about_button, "about_button");
  GLADE_HOOKUP_OBJECT (main_window, close_button, "close_button");

  gtk_widget_grab_focus (about_button);
  gtk_widget_grab_default (about_button);
  return main_window;
}

